# Generated by Django 4.1.2 on 2022-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_player_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("profession", models.CharField(max_length=100)),
                ("telephonNumber", models.CharField(max_length=100)),
                ("mobileNumber", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Player",
        ),
    ]
